# -*- coding: utf-8 -*-
"""automate_Nida.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WHXpUEd1iE_ZWP_vZXWuRtPYzSeTDa2g
"""

import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder


def load_data(file_path):
    print("Membaca data mentah...")
    return pd.read_csv(file_path, sep=';')


def categorize_anxiety(x):
    if x <= 3:
        return 0   # Low Anxiety
    elif x <= 7:
        return 1   # Medium Anxiety
    else:
        return 2   # High Anxiety


def preprocess_data(df):
    print("Memulai proses preprocessing data...")

    # 1. Rapikan nama kolom
    df.columns = df.columns.str.strip()

    # 2. Hapus missing values jika ada
    df = df.dropna()

    # 3. Hapus data duplikat
    df = df.drop_duplicates()

    # 4. Encoding data kategorikal
    categorical_cols = [
        'Gender',
        'Occupation',
        'Smoking',
        'Family History of Anxiety',
        'Dizziness',
        'Medication',
        'Recent Major Life Event'
    ]

    le = LabelEncoder()

    for col in categorical_cols:
        if col in df.columns:
            df[col] = le.fit_transform(df[col].astype(str))

    # 5. Transform target menjadi kategori
    target_col = 'Anxiety Level (1-10)'

    if target_col not in df.columns:
        raise ValueError(f"Kolom target '{target_col}' tidak ditemukan.")

    df['Anxiety Category'] = df[target_col].apply(categorize_anxiety)

    # 6. Pastikan seluruh data numerik
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = le.fit_transform(df[col].astype(str))

    print("Preprocessing data selesai.")
    return df


def save_data(df, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False)

    print(f"Data hasil preprocessing berhasil disimpan di: {output_path}")
    print(f"Shape data hasil preprocessing: {df.shape}")


if __name__ == "__main__":
    # Path dinamis agar bisa berjalan di lokal dan GitHub Actions
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    input_file = os.path.join(
        base_dir,
        'namadataset_raw',
        'social_anxiety_dataset.csv'
    )

    output_file = os.path.join(
        base_dir,
        'preprocessing',
        'namadataset_preprocessing',
        'social_anxiety_preprocessed.csv'
    )

    raw_data = load_data(input_file)
    processed_data = preprocess_data(raw_data)
    save_data(processed_data, output_file)